assets:
  overrides:
    /: frontend/

server:
  rootPath: '/api/*'
 

database:
  driverClass: com.mysql.jdbc.Driver
  #your database username
  user: root
  #your database password
  password: 2001
  #your database url
  url: jdbc:mysql://localhost:3306/whtsondb
  properties:
    charSet: UTF-8